### ISSUE TITLE
unmount only one remote NFS dir fails.

### ISSUE THREAD

**Issue by fghoraishi** [IBM/ansible-power-aix#111]
Trying to use the amount option to unmount one remote NFS mounted directory.
It only allows me to unmount all remote directories via the mount_all: remote option.

How can I just unmount on remote directory?

Thanks

This is my playbook:

name: Unmount remote filesystems
ibm.power_aix.mount:
state: umount
mount_dir: /mnt

**Comment by jdejoya17** [comment]
Hello Faad, thanks for contacting us.
I am trying to recreate your issue.
In my case it seems to be working fine.

below is some of the output of `mount`
```
xxxxxxxx /tmp/servnfs     /tmp/clientnfs   nfs3   Jun 22 15:55
```
here you see /tmp/clientnfs is the mount point of the remote filesystem
and /tmp/servnfs is the mount point of the backing fs from the remote node

now running my playbook
```
---
- name: "unmount remote filesystems"
  hosts: xxxxxxx
  remote_user: root
  gather_facts: False
  collections:
  - ibm.power_aix
  
  tasks:
  - name: "unmount NFS filesystem"
    mount:
      state: umount
      mount_dir: /tmp/clientnfs
``` 
which is the same as yours

ansible result:
```
PLAY [unmount remote filesystems] *******************************************************************

TASK [unmount NFS filesystem] ***********************************************************************
ok: [x.x.x.x]

PLAY RECAP ******************************************************************************************
x.x.x.x                : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

checking in my node where the remote fs used to be mounted
```
# mount | grep /tmp/clientnfs

```

it is not there anymore. it looks like it is working. can you tell us more how to recreate the problem.
