### ISSUE TITLE
mount: Ansible change state

### ISSUE THREAD

**Issue by McBschire** [IBM/ansible-power-aix#158]
**Describe the bug**
(A) The `state: mount` does not act idempotent. Several executions result into `changed=true`, even if it is already mounted.
(B) The `state: umount` shows `ok=true`, even if it in fact did an umount of a previously mounted filesystem.

(A):
**To Reproduce**
1. Filesystem not mounted.
2. Run playbook to mount.
```
- name: 'mount/umount NFSv4 filesystem'
  ibm.power_aix.mount:
    options: 'vers=4'
    mount_dir: '/REMOTEPATH'
    mount_over_dir: '/LOCALPATH'
    node: 'HOSTNAME'
    state: 'mount'
```
3. results in `changed=true`
4. Run playbook to mount again
```
- name: 'mount/umount NFSv4 filesystem'
  ibm.power_aix.mount:
    options: 'vers=4'
    mount_dir: '/REMOTEPATH'
    mount_over_dir: '/LOCALPATH'
    node: 'HOSTNAME'
    state: 'mount'
```
5. Result in `changed=true`
**Expected behavior**
but should be `ok=true`

(B):
**To Reproduce**
1. Filesystem  mounted.
2. Run playbook to umount.
```
- name: 'mount/umount NFSv4 filesystem'
  ibm.power_aix.mount:
    options: 'vers=4'
    mount_dir: '/REMOTEPATH'
    mount_over_dir: '/LOCALPATH'
    node: 'HOSTNAME'
    state: 'umount'
```
3. results in `ok=true`
**Expected behavior**
but should be `changed=true`

**Environment (please complete the following information):**
 - OS: AIX [7.2.0.0]
 - Python Version: [3.9.1]
 - OpenSSH Version: [8.1.102]
 - Ansible Version: [2.9.24]
 - AIX Collection Version: [1.2.1]
