### ISSUE TITLE
Feature Request/Discussion: chsec re-re-PR

### ISSUE THREAD

**Issue by d-little** [IBM/ansible-power-aix#164]
**Is your feature request related to a problem? Please describe.**
Nope - New Module discussion

**Describe the solution you'd like**
A number of years ago @flynn1973 put together a Ansible module to act as a wrapper for the AIX `chsec` command.

A good while later that I re-submitted it to Ansible to be included, but Collections threw a spanner in the works. 

Now that things have settled down a bit, and I'm back to actively using Ansible with AIX, I'd now like suggest it again.  This issue is for sending out feelers/discussion to see if it is desired.  If yes, I'll continue to work on this module and submit a PR to have it added to ansible-power-aix.

**Describe alternatives you've considered**
I _believe_ this would be a new feature for the `ansible-power-aix`, and it's _mostly_ written.  I'll just need to work on bringing it up to code, so to speak.

**Additional context**
The original PR is here: https://github.com/ansible/ansible/pull/60976

I've copied it below for prosperity: 

----

**SUMMARY**

Updated code from stale PR #49057 : adds stanzas to aix config files using the chsec command.

**Features:**

- Fully idempotent
- Check mode
- Updated docs

Full details below.

**ISSUE TYPE**

- New Module Pull Request

**COMPONENT NAME**

aix_chsec.py

**ADDITIONAL INFORMATION**
**Idempotency**

We make the tool idempotent by first checking the output of `[lssec](https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/com.ibm.aix.cmds3/lssec.htm)` before running chsec

**Using the module**

One example implementation with multiple key/value being set within a single file+stanza:
```yaml
- name: Name of Task
  aix_chsec:
    file: filename
    stanza: stanzaname
    attrs:
      key1: value1
      key2: value2
      keyN: valueN
    state: [ present, absent ]
```
NB: `attr` are changes made one at a time in code

This would return `Changed` if any number of the above key/value pairs were changed. If none were changed status would be `OK`. Failure to change any key:value pair would constitute as a `failure` **at the time of failure** _regardless of how many attributes were successfully set_.

- `attrs` has the alias options
- Valid `attrs` formats:
```
attrs:
  key: value
  key2: value2

[key=value, key=value]

"key=value, key=value"
```

**Real world use:**

- Allow logins from 8:00 a.m. until 5:00 p.m. for all users
- Change the CPU time limit of user joe AND charlie to 1 hour (3600 seconds):

```yaml
---
- hosts: targetserver
  gather_facts: no
  vars:
    example_chsec:
      - file: /etc/security/user
        stanza: default
        attrs:
          logintimes: ":0800-1700"
      - file: /etc/security/limits
        stanza: joe
        attrs: cpu=3600
      - file: /etc/security/limits
        stanza: charlie
        attrs:
          cpu: 3600
  remote_user: deploy
- tasks:
  name: Example chsec
    aix_chsec:
      file: "{{ item.file }}"
      stanza: "{{ item.stanza }}"
      attrs: "{{ item.attrs }}"
    loop:
      - "{{ example_chsec }}"
```

**Future Ideas**
**Backup**

Have a flag `backup=true` to create a backup of the `file` before making changes

**'Nested' Stanzas**

We could 'nest' stanzas for a single file within a single module call. This increases the chances of any one attribute failing. We can keep the `stanza` option available in addition to `stanza`s, mutually exclusive.

```yaml
- name: Name of Task
  aix_chsec:
    file: filename
    stanzas:
      - stanza1:
          key1: value1
          key2: value2
          keyN: valueN
        state: [ present|absent ]
      - stanza2:
          key1: value1
          key2: value2
          keyN: valueN
        state: [ present|absent ]
    backup: bool (default no, timestamped backup before making changes.)
```
