### ISSUE TITLE
Add UID for User Creation

### ISSUE THREAD

**Issue by gdelbrusco** [IBM/ansible-power-aix#190]
A good idea is to add UserID on the module user.py

**Comment by MBlenn** [comment]
@pvtorres 
Hi Pedro,
in general the user ID support seems to be in place, right?
Modifying an existing user works for me, the ID is updated in /etc/passwd. 
When creating a user using the ID attribute it works for very simple users, but as soon as pgrp, groups, home, shell or umask are added the task fails (even though the user is created):
`fatal: [testserver]: FAILED! => {"changed": false, "msg": "\nFailed to modify attributes for the user: testuser123", "rc": 17, "stderr": "3004-692 Error changing \"id\" to \"1555\" : Account exists.\n", "stderr_lines": ["3004-692 Error changing \"id\" to \"1555\" : Account exists."], "stdout": "", "stdout_lines": []}
`
is there still some work needed internally to set these in one go or maybe just catch that error?
The user is created and when rerun with "retries: 1" and "until: result is not failed" I can still turn the task green, but that is a bit of a work around ;-)

regards,
Martin

**Comment by pvtorres** [comment]
Hi Martin, 
Can you provide the playbook task that you are using when modifying and existing user? 
I am trying to recreate the problem. So I need to create a user where I input the ID I want. And that ID is not currently used by any other user. If the task is simple, it will work. But if I delete that user and try it again, this time with more complex attribute such as pgrp, groups home, shell or umask (Any of them or combined?) It will fail.

**Comment by pvtorres** [comment]
I tried to crate a user with the id, group and shell. So far it seems to be working. 

Playbook:
  - name: create user
    ibm.power_aix.user:
      state: present
      name: test1
      password: "{{ aix_enc_passwd_v }}"
      attributes:
         id: "{{ uid }}"
         groups: "{{ group_list }}"
         shell: "/usr/bin/ksh"
         
         output:

changed: [test1.ibmm.com] => changed=true 
  invocation:
    module_args:
      attributes:
        groups: system
        id: '1234'
        shell: /usr/bin/ksh
      change_passwd_on_login: false
      name: tester
      password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      remove_homedir: true
      state: present
  msg: |-
    Username is created SUCCESSFULLY: tester
    Password is set successfully for the user: tester

Please also tell me which AIX OS level do you have. I tested the code with the latest AIX collection 1.5.0.

**Comment by MBlenn** [comment]
Hi @pvtorres,

thanks for looking into this, sorry for the late reply!

My test systems were 7200-05-03-2148. 
I have meanwhile updated my collection to 1.5.0 as well and am typically using the ibm.power_aix.user with the attributes shown below:

```
    - 
      name: 'Creating test1000'
      ibm.power_aix.user:
        state: present
        name: 'test1000'
        change_passwd_on_login: False
        password: "{{ password }}"
        attributes:
          shell:  '/bin/csh'
          id:     '1000'
          pgrp:   'sapsys'
          groups: 'sapsys,sapinst'
          home:   '/home/test1000'
          umask:  '022'
```

Luckily now the problem no longer persists, the user is created on the first try, no more errors are shown that would require a retry to get the task completed. 

Thank you!
