### ISSUE TITLE
error is not reported in nim module

### ISSUE THREAD

**Issue by aklyachkin** [IBM/ansible-power-aix#193]
**Describe the bug**
A small playbook is run (code see below) and returns "OK", but nothing happens. If it is run with -vvv (very verbose), there is an error in meta information:

```
    "meta": {
        "nimclient": {
            "messages": [
                "Cannot get oslevel from lpp source name: 7200-02-02-1832_current"
            ]
        },
        "messages": []
    },
    "msg": "NIM update operation successfull. See status and meta for details.",
```

**To Reproduce**
Code:
```
- hosts: localhost
  collections:
  - ibm.power_aix

  tasks:
  - name: update AIX server
    ibm.power_aix.nim:
      action: update
      targets: nimclient
      lpp_source: 7200-02-02-1832_current
```
<img width="1251" alt="grafik" src="https://user-images.githubusercontent.com/3786052/158156389-eeaf7ae0-bd36-4031-9ed6-5cc6043691fd.png">

**Expected behavior**
The task should fail and the error message should be shown.

**Environment (please complete the following information):**
 - OS: AIX 7.3 TL0 SP1
 - Python Version: 3.7.12
 - OpenSSH Version: 8.1.102.2104
 - Ansible Version: 2.9.14
 - AIX Collection Version: 1.4.0
