### ISSUE TITLE
ibm.power_aix.suma - TypeError: '>' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by dfmateus** [IBM/ansible-power-aix#194]
**Describe the bug**
Hello,

I tried to use the **ibm.power_aix.suma** module for download only the latest version of TL/SP and getting the error below.

`TASK [ansible-testing-tower : Download Latest TL/SP 7200-05, Please wait...] ***********************************************************************************
Monday 11 April 2022  18:35:57 -0300 (0:00:00.141)       0:01:38.359 **********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: '>' not supported between instances of 'NoneType' and 'str'
fatal: [g42p-a-00000323.az2.ash.cpc.ibm.com]: FAILED! => changed=false
  module_stderr: |-
    Connection to g42p-a-00000323.az2.ash.cpc.ibm.com closed.
  module_stdout: |-
    Traceback (most recent call last):
      File "/home/ansible/.ansible/tmp/ansible-tmp-1649712959.7918131-23865-187329735706634/AnsiballZ_suma.py", line 107, in <module>
        _ansiballz_main()
      File "/home/ansible/.ansible/tmp/ansible-tmp-1649712959.7918131-23865-187329735706634/AnsiballZ_suma.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/ansible/.ansible/tmp/ansible-tmp-1649712959.7918131-23865-187329735706634/AnsiballZ_suma.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ibm.power_aix.plugins.modules.suma', init_globals=dict(_module_fqn='ansible_collections.ibm.power_aix.plugins.modules.suma', _modlib_path=modlib_path),
      File "/opt/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/opt/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/opt/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ibm.power_aix.suma_payload_s94i4v1o/ansible_ibm.power_aix.suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/suma.py", line 915, in <module>
      File "/tmp/ansible_ibm.power_aix.suma_payload_s94i4v1o/ansible_ibm.power_aix.suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/suma.py", line 905, in main
      File "/tmp/ansible_ibm.power_aix.suma_payload_s94i4v1o/ansible_ibm.power_aix.suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/suma.py", line 693, in suma_download
      File "/tmp/ansible_ibm.power_aix.suma_payload_s94i4v1o/ansible_ibm.power_aix.suma_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/suma.py", line 357, in compute_rq_name
    TypeError: '>' not supported between instances of 'NoneType' and 'str'
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1`

My playbook is:
```
- name: suma - Download/Install fixes, SP or TL from IBM Fix Central website.
  hosts: all
  gather_facts: true

- name: Download Latest TL/SP 7200-05, Please wait...
  become: true
  ibm.power_aix.suma:
    action: download
    oslevel: 7200-05
    last_sp: yes
    download_only: yes
    extend_fs: yes
    download_dir: /tmp/7200-05-LATEST
  register: output
```

**Environment (please complete the following information):**
 - OS: [7200-05-02-2114]
 - Python Version: [3.9.1]
 - OpenSSH Version: [8.1.102.2104]
 - Ansible Version: [core 2.12.1]]
 - AIX Collection Version: [1.4.0]

**Additional context**
