### ISSUE TITLE
ibm.power_aix.lvg wont work in loop

### ISSUE THREAD

**Issue by MBlenn** [IBM/ansible-power-aix#197]
### Hello team,
first of all thanks a lot for providing this collection!

**Describe the bug**
In a playbook for PowerHA SmartAssist for SAP automation I am creating users, lvs and file systems through respective modules in ansible-power-aix. I am using loops to keep the yaml nice and clean. 
However, using ibm.power_aix.lvg with exact same syntax that works with the other modules, I am getting the below error:

```
TASK [Creating VGs] *****************************************************************************************************************************************************************************************
fatal: [aixtestserver]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'major_num'\n\nThe error appears to be in '/home/xxx/ansible/SAP-NW-HA/create_fs.yml': line 17, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  -\n    name: 'Creating VGs'\n    ^ here\n"}
```

**To Reproduce**
This works perfectly:  
``` 
  -
    name: 'Create volume group saplocalvg'
    ibm.power_aix.lvg:
      pvs=hdisk4
      vg_name='saplocalvg'
      auto_on=no
      pp_size=128
      major_num=101
      vg_type=scalable
      enhanced_concurrent_vg=no
      state=present
```
This doesn't: 
```
  -
    name: 'Creating VGs'
    ibm.power_aix.lvg: vg_name='{{ item.vg_name }}' auto_on='{{ item.auto_on }}' major_num='{{ item.major_num }}' vg_type='scalable' enhanced_concurrent_vg='{{ item.ec_vg }}' pvs='{{ item.pvs }}' state='present'
    loop:
      - { vg_name: 'saplocalvg',        auto_on: 'yes', pp_size='128', major_num='101', ec_vg='no',  pvs: 'hdisk3' }
      - { vg_name: '{{SIDlower}}nfsvg', auto_on: 'no',  pp_size='128', major_num='102', ec_vg='yes', pvs: 'hdisk4' }
```
Please see the error above.

If I eg. make the pp_size static, it complains about the ec_vg.

**Expected behavior**
Create VG same way as it is perfectly working when using a single task per VG:

**Environment (please complete the following information):**
 - OS: 7200-05-03-2135
 - Python Version: 2.7.15
 - OpenSSH Version: OpenSSH_8.1p1
 - Ansible Version: 2.9.27
 - AIX Collection Version: 1.4.0

Best regards, 
Martin

**Comment by jdejoya17** [comment]
Hi @MBlenn ,

Thank you for using our collection. I have tried to recreate the issue and did not find a problem.
```
$ ansible-playbook -i hosts playbooks/issue197.yml 
[WARNING]: running playbook inside collection ibm.power_aix
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [testing issue 197] ***********************************************************************************************************************************************************************************

TASK [create volume group saplocalvg] **********************************************************************************************************************************************************************
changed: [x.x.x.x] => (item={'vg_name': 'saplocalvg1', 'auto_on': 'yes', 'pp_size': '128', 'major_num': '101', 'ec_vg': 'no', 'pvs': 'hdisk1'})
changed: [x.x.x.x] => (item={'vg_name': 'saplocalvg2', 'auto_on': 'no', 'pp_size': '128', 'major_num': '102', 'ec_vg': 'yes', 'pvs': 'hdisk2'})

PLAY RECAP *************************************************************************************************************************************************************************************************
x.x.x.x                : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

However, notice in your loop dictionary:

```
...
 loop:
      - { vg_name: 'saplocalvg',        auto_on: 'yes', pp_size='128', major_num='101', ec_vg='no',  pvs: 'hdisk3' }
      -                                                                                     ^^^ you are using equal (=) instead of colon (:) here
      - { vg_name: '{{SIDlower}}nfsvg', auto_on: 'no',  pp_size='128', major_num='102', ec_vg='yes', pvs: 'hdisk4' }
```

this is an invalid yaml dictionary format. hence you are getting the error.

i can provide my working task below as a reference:
```
  tasks:
    - name: "create volume group saplocalvg"
      ibm.power_aix.lvg:
        vg_name: "{{ item.vg_name }}"
        auto_on: "{{ item.auto_on }}"
        major_num: "{{ item.major_num }}"
        vg_type: "scalable"
        enhanced_concurrent_vg: "{{ item.ec_vg }}"
        pvs: "{{ item.pvs }}"
        state: "present"
      loop:
        - { vg_name: "saplocalvg1", auto_on: "yes", pp_size: "128", major_num="101", ec_vg: "no", pvs: "hdisk1" }
        - { vg_name: "saplocalvg2", auto_on: "no", pp_size: "128", major_num: "102", ec_vg: "yes", pvs: "hdisk2" }
```

Let us know if there is still an issue after fixing the loop dictionary. Otherwise, we can close the issue.
Thank you for your usage in our collection.

Joseph
