### ISSUE TITLE
device module option "chtype: reboot" not idempotent

### ISSUE THREAD

**Issue by scheurer13** [IBM/ansible-power-aix#257]
Change a aix device with option "chtype: reboot" the task always is changed. Regardless of whether the parameter is already correct or has already been set.

```
    - name: change ent to mac_swap=yes
      ibm.power_aix.devices:
        device: '{{ item }}'
        attributes:
          mac_swap: 'yes'
        state: 'available'
        chtype: 'reboot'
      loop: "{{ entlist.stdout_lines }}"
```
Verbose Log:

```
changed: [sps94291] => (item=ent8) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "attributes": {
                "mac_swap": "yes"
            },
            "chtype": "reboot",
            "device": "ent8",
            "force": false,
            "parent_device": null,
            "recursive": false,
            "rmtype": "unconfigure",
            "state": "available"
        }
    },
    "item": "ent8",
    "msg": "Modification of Device attributes completed for device 'ent8'"
}
```

**Expected behavior**
Task shoud be ok when attribute is already correct.

**Environment (please complete the following information):**
 - OS: 7200-05-04-2220
 - Python Version: Python 2.7.18
 - Ansible Version: ansible [core 2.11.8]
 - AIX Collection Version: ibm.power_aix           1.5.1
