### ISSUE TITLE
Unable to modify an entry with module inittab

### ISSUE THREAD

**Issue by christophegehin** [IBM/ansible-power-aix#341]
**Describe the bug**
Unable to modify an entry with module inittab

**To Reproduce**
Use that task in a playbook
  - name: debug
    ibm.power_aix.inittab:
      state: modify
      name: nimsh
      runlevel: '23'
      command: '/usr/bin/startsrc -e "LIBPATH=/usr/lib" -g nimclient >/dev/console 2>&1'
      action: wait

**Expected behavior**
No error and entry changed successfully

**Screenshots**
Error: 
fatal: [netapp7n05m]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "wait",
            "command": "/usr/bin/startsrc -e \"LIBPATH=/usr/lib\" -g nimclient >/dev/console 2>&1",
            "insertafter": null,
            "name": "nimsh",
            "runlevel": "23",
            "state": "modify"
        }
    },
    "msg": "\nFailed to change the entry in inittab file: nimsh",
    "rc": 1,
    "stderr": "chitab: 0481-203 Cannot specify more than one parameter.\nUsage:\tchitab \"ident:runlevel:action:command\"\n",
    "stderr_lines": [
        "chitab: 0481-203 Cannot specify more than one parameter.",
        "Usage:\tchitab \"ident:runlevel:action:command\""
    ],
    "stdout": "",
    "stdout_lines": []
}

**Environment (please complete the following information):**
 - OS: 7.2.5.6
 - Python Version: 3.9.17
 - OpenSSH Version: 9.2.112.2000
 - Ansible Version: 2.11.12
 - AIX Collection Version: 1.6.4

**Comment by neikei** [comment]
I can confirm this bug, because the values for the "command" are not processed properly.

Test 1: command contains a single path => OK
```yaml
# Example
"command": "/usr/sbin/uprintfd

# Result
$ grep uprintfd /etc/inittab
uprintfd:1234567:respawn:/usr/sbin/uprintfd
```

Test 2: command contains a path and output redirections => Task shows success, but the inittab isn't updated
```yaml
# Example
    "invocation": {
        "module_args": {
            "action": "respawn",
            "command": "/usr/sbin/uprintfd >/dev/console 2>&1",
            "insertafter": null,
            "name": "uprintfd",
            "runlevel": "1234567",
            "state": "modify"
        }
    },
    "msg": "\nEntry for: uprintfd is changed SUCCESSFULLY in inittab file"

# Result
$ grep uprintfd /etc/inittab
uprintfd:1234567:respawn:/usr/sbin/uprintfd
```

Test 3: command contains complex values like " and "=" => Task failed and it looks like several strings are passed to the commandline
```yaml
# Example
    "invocation": {
        "module_args": {
            "action": "respawn",
            "command": "/usr/sbin/uprintfd \"PATH=/opt\" >/dev/console 2>&1",
            "insertafter": null,
            "name": "uprintfd",
            "runlevel": "1234567",
            "state": "modify"
        }
    },
    "msg": "\nFailed to change the entry in inittab file: uprintfd",
    "rc": 1,
    "stderr": "chitab: 0481-203 Cannot specify more than one parameter.\nUsage:\tchitab \"ident:runlevel:action:command\"\n",
    "stderr_lines": [
        "chitab: 0481-203 Cannot specify more than one parameter.",
        "Usage:\tchitab \"ident:runlevel:action:command\""
    ],
```

Tested with collection version "1.6.1", but inittab was updated the last time on May 18, 2022.
