### ISSUE TITLE
Creating group with an existing GID fails but group is created

### ISSUE THREAD

**Issue by aklyachkin** [IBM/ansible-power-aix#361]
**Describe the bug**

Use ibm.power_aix.group to create a new group with some GID. If GID is already used by another group, the module fails but the group is created anyway with wrong GID.

**To Reproduce**

1. Create some group on AIX with GID:
```
mkgroup -a id=1000 group1
```
2. Create test playbook:
```yaml
---
- name: Test case for ibm.power_aix.group
  hosts: all
  gather_facts: false

  tasks:
  - name: Create a new group with existing GID
    ibm.power_aix.group:
      name: group2
      state: present
      group_attributes:
        id: 1000
```
3. Run the playbook
```
ansible-playbook -i localhost, -c local group_test.yml
```
4. See the error
```
fatal: [server]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/opt/freeware/bin/python3.9"}, "changed": true, "cmd": "c h g r o u p   i d = 1 0 0 0     g r o u p 2", "msg": "\nFailed to modify attributes for group: group2.", "rc": 17, "stderr": "Error changing \"id\" to \"1000\" : Account exists.\n", "stderr_lines": ["Error changing \"id\" to \"1000\" : Account exists."], "stdout": "", "stdout_lines": []}
```
5. Look at the list of the groups on AIX. Group2 is created but with wrong GID:
```
# lsgroup -a id ALL | grep group[12]
group1 id=1000
group2 id=210
```

**Expected behavior**
The group group2 is not created.

**Environment (please complete the following information):**
 - OS: AIX 7.3 TL1 SP2
 - Python Version: 3.9
 - Ansible Version: 2.14.2
 - AIX Collection Version: 1.7.0

**Additional context**
The module does the work in two steps. First it executes mkgroup without any attributes and then if it gets any attributes from the playbook it executes chgroup. It must be changed in either of two ways:
- Create the group with attributes (mkgroup -a ...)
- Remove the group if changing of attributes was not successful (rmgroup in case of the failure)
