### ISSUE TITLE
lvol does not allow renaming with out specifying size

### ISSUE THREAD

**Issue by Findarato** [IBM/ansible-power-aix#372]
**Describe the bug**

**To Reproduce**
```
    - name: Correct logical volume name
      become: True
      ibm.power_aix.lvol:
        vg: "{{ item.volume_group }}"
        lv: "{{ item.logical_volume }}"
        lv_new_name: "{{ item.logical_volume_new_name }}"
        state: present
```

**Expected behavior**
The logical volume is renamed

**Screenshots**
```
failed: item
  cmd: ''
  item:
    logical_volume: oldname
    logical_volume_new_name: newname
    volume_group: volumegroupname
  msg: |2-
  
    Reducing the size of the logical volume is not supported.
  rc: 0
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Csize:          383968
    PPsize:         25
  stdout_lines: <omitted>
```

**Environment (please complete the following information):**
 - Ansible Version: ansible [core 2.14.8]
 - AIX Collection Version: anything higher than 1.2

**Additional context**
I have tested every released version above 1.2 and they all have the same problem.  Something regressed past 1.2
