### ISSUE TITLE
Allow emgr to accept list of files as list and not just as file

### ISSUE THREAD

**Issue by syahrul-aiman** [IBM/ansible-power-aix#385]
referring to the `emgr` module.

currently, the module accepts `list_file` as parameter which takes a file, containing a list of paths or labels.

Instead of this, can you create another parameter such as `ifix_packages` (or reuse the same parameter) to accept list of paths to the ifixes?

With that, it will create a temporary file containing this list of paths, which emgr will use -f to execute as well.

Example:

```yaml
- name: install fixes
  ibm.power_aix.emgr:
    action: install
    from_epkg: true
    ifix_packages:
      - /usr/sys/inst.images/IJ43869m5b.230216.epkg.Z
      - /usr/sys/inst.images/IJ42339s5a.221212.epkg.Z
    extend_fs: true
  register: results
```
