### ISSUE TITLE
install_all_updates not returning Changed when the task updated some software

### ISSUE THREAD

**Issue by lionelwidmer** [IBM/ansible-power-aix#513]
**Describe the bug**
The task:
```
- name: Update EMC ODM definitions
  ibm.power_aix.install_all_updates:
    device: "{{ emc_odm_path }}"
    agree_licenses: True
    commit: True
  become: True
  register: emc_odm
```
When something has been done (some software got updated by the task), it returns Ok, but when nothing has been done by the task, it returns Changed
