### ISSUE TITLE
Regression in the user module between 1.9.x and 2.0.x

### ISSUE THREAD

**Issue by aklyachkin** [IBM/ansible-power-aix#637]
**Describe the bug**
Playbook changing multiple user attributes simultaneously doesn't work after upgrading ibm.power_aix collection to 2.0.x

**To Reproduce**
- create a user on AIX and set some attributes
- create small playbook to change some of attributes
- install older ibm.power_aix collection, everything works
- change the attributes back
- install newer ibm.power_aix collection, the playbook fails

User example:

<img width="2485" alt="Image" src="https://github.com/user-attachments/assets/b7d73218-696b-4049-82bd-61f70f1ca7b0" />

The playbook:

```yaml
---
- name: Set user attributes
   hosts: all
   gather_facts: false

   tasks:
     - name: Set user attributes
       ibm.power_aix.user:
         name: andrewk
         state: present
         attributes:
           gecos: Andrey Klyachkin
           shell: /usr/bin/ksh93
           maxage: 0
           histsize: 0
```

Install ibm.power_aix 1.9.2:

```
ansible-galaxy collection install ibm.power_aix:==1.9.2 -p ./collections
```

Run the playbook:

<img width="1267" alt="Image" src="https://github.com/user-attachments/assets/b4a8be05-4f7e-4df5-801a-ef79512b7261" />

Everything works as expected.

Change the attributes back on AIX:

<img width="628" alt="Image" src="https://github.com/user-attachments/assets/63b3d97a-fa38-4ba7-9d23-4dfc1c8ca67f" />

Upgrade ibm.power_aix collection to 2.0.3:

```
ansible-galaxy collection install ibm.power_aix:==2.0.3 -p ./collections
```

Rerun the playbook:

<img width="2485" alt="Image" src="https://github.com/user-attachments/assets/212561b2-c51d-4260-9c7a-acb78a6dcb56" />

The playbook fails.

**Expected behavior**
The playbook works consistently and changes the user's attributes.

**Environment (please complete the following information):**
 - OS: AIX 7.3 TL3
 - Python Version: AIX-supplied, 3.9
 - Ansible Version: 2.13.11
 - AIX Collection Version: 2.0.3

**Additional context**
The problem seems to be in the line 174 of user.py:

```python
        if str(user_attrs[attr]) != str(val):
            opts += f"{attr}=\"{val}\" "
            opts = load_module_opts + opts
```

The line add load_module_opts (e.g. -R files) to each attribute to change. At the end the command looks like:

```
chuser -R files shell=/usr/bin/ksh93 -R files maxage=0 -R files histsize=0
```

Commenting the line out helps to solve the problem.

The load_module_opts should go into the line 179:

```python
    if opts:
        cmd = f"chuser {opts} {name}"
```

should be:

```python
    if opts:
        cmd = f"chuser {load_module_opts} {opts} {name}"
```
