### ISSUE TITLE
Add 'defaults' support to ibm.power_aix.devices

### ISSUE THREAD

**Issue by lewus** [IBM/ansible-power-aix#651]
**Is your feature request related to a problem? Please describe.**
Implement 'defaults' values to ibm.power_aix.devices (see chdef command)
The request was already created for community.general.aix_devices, but never implemented:
[https://github.com/ansible/ansible/issues/59110](https://github.com/ansible/ansible/issues/59110)

**Describe the solution you'd like**
Something like:
```
- name: Change default disk algorithm
  aix_devices:
    device: default
    class: disk
    subclass: fcp
    type: mpioosdisk
    attrs: 
      algorithm: shortest_queue
    state: available
```
where `device == default` instead switches to changing default values.

**Describe alternatives you've considered**
An alternative is to use the ansible.builtin.command module, but that is not elegant and not idempotent.
Example:
```
- name: Set default policy to no_reserve for SVC disks
  ansible.builtin.command:
    cmd: chdef -a reserve_policy=no_reserve -c disk -s fcp -t mpioosdisk
```

**Additional context**
-
