### ISSUE TITLE
Module group is not idempotent

### ISSUE THREAD

**Issue by aklyachkin** [IBM/ansible-power-aix#670]
**Describe the bug**
If group attributes are specified, the module brings an error during the 2nd run like:

```
fatal: [10.1.0.1]: FAILED! => {"changed": false, "cmd": "chgroup  -R files  id=1000  gitlab", "msg": "Group gitlab already exists.\nFailed to modify attributes for group: gitlab.", "rc": 17, "stderr": "Error changing \"id\" to \"1000\" : Account exists.\n", "stderr_lines": ["Error changing \"id\" to \"1000\" : Account exists."], "stdout": "", "stdout_lines": []}
```

**To Reproduce**
1. The playbook:
```yaml
---
- name: Create the group
  hosts: all
  remote_user: root
  gather_facts: false

  tasks:
    - name: Create gitlab group
      ibm.power_aix.group:
        name: gitlab
        state: present
        group_attributes:
          id: 1000
```

2. Run the playbook for the first time. The group is created.
3. Run the playbook for the second time. The error above is shown, and the playbook is aborted.

**Expected behavior**
The module detects that the group already has the correct attributes set and returns OK.

**Screenshots**

**Environment (please complete the following information):**
 - OS: AIX 7.2.5.8 (maanged node) / Ubuntu Linux 24.04.2 (controller)
 - Python Version: 3.9.16 (managed node) / 3.12.3 (controller)
 - OpenSSH Version: N/A
 - Ansible Version: 2.16.3
 - AIX Collection Version: 2.1.1
