### ISSUE TITLE
filesystem creation does not support existing LV

### ISSUE THREAD

**Issue by MaartenKreuger** [IBM/ansible-power-aix#73]
The filesystem.py module does not support creating a filesystem on an existing LV. I added code to allow the -d option to be added. 
[filesystem.txt](https://github.com/IBM/ansible-power-aix/files/6050007/filesystem.txt)

**Comment by jdejoya17** [comment]
Creating a filesystem on an existing LV is supported. You have to specify the `device` parameter.
Check sample playbook below

```
---
- hosts: lp3
  gather_facts: no
  remote_user: root

  tasks:
    - name: "Create JFS2 File System on an existing LV"
      ibm.power_aix.filesystem:
        state: present
        filesystem: /tmp/issue73
        device: testlv73 # specifying an existing LV (testlv73)
```
