### ISSUE TITLE
ibm.power_aix.filesystem reports changes when none occur

### ISSUE THREAD

**Issue by stephenulmer** [IBM/ansible-power-aix#76]
**Describe the bug**
ibm.power_aix.filesystem reports changed when doing nothing.

**To Reproduce**

Run this play twice in succession:
```
---
- hosts: rdu1
  gather_facts: no
  vars:
    example_size: 5G
  tasks:
    - name: Create File System
      ibm.power_aix.filesystem:
        state: present
        filesystem: /export/example
        vg: rootvg
        attributes: "size={{ example_size }}"
        auto_mount: yes
```

**Expected behavior**
The task should not report that anything has changed on subsequent runs (when nothing has changed).

**Screenshots**
First run:
```
PLAY [rdu1] **********************************************************************************************************

TASK [Create File System] ********************************************************************************************
changed: [rdu1]

PLAY RECAP ***********************************************************************************************************
rdu1                       : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

All subsequent runs:
```
PLAY [rdu1] **********************************************************************************************************

TASK [Create File System] ********************************************************************************************
changed: [rdu1]

PLAY RECAP ***********************************************************************************************************
rdu1                       : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Environment (please complete the following information):**
 - OS: AIX 7200-05-01-2038
 - Python Version: 2.7.10 (installed at the same time as YUM)

**Additional context**
These things do not change the problem:
  - mounting the file system in between runs
  - gather_facts: yes
