### ISSUE TITLE
Moun

### ISSUE THREAD

**Issue by Findarato** [IBM/ansible-power-aix#88]
**Describe the bug**
Mount is giving an error when I am trying to unmount a filesystem

**To Reproduce**

**Expected behavior**
Disk should be unmounted

**Screenshots**

Playbook
```
 tasks:
    - name: Umount filesystems
       become: true
       ibm.power_aix.mount:
        mount_dir: /dev/fspure_dr_data0
        state: umount

```

```
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  cmd: df
  msg: Failed to get the filesystem name. Command 'df' failed.
  rc: 1
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Filesystem    512-blocks      Free %Used    Iused %Iused Mounted on
    /dev/hd4         1572864    948664   40%    20679    16% /
    /dev/hd2        50331648  27526752   46%    67013     3% /usr
    /dev/hd9var      5242880   3450168   35%     4487     2% /var
    /dev/hd3          524288    237552   55%     1077     4% /tmp
    /dev/hd1        41943040  25919024   39%     1911     1% /home
```

**Environment (please complete the following information):**
 - OS: AIX 7200-04-02-2028
 - Python Version: Python 2.7.10
 - OpenSSH Version: [e.g. 1.0.2]
 - Ansible Version: ansible 2.9.20
 - AIX Collection Version: Newest on Galaxy 2021-05-04

**Additional context**

I have tired with the filesystem both mounted and unmounted, both gave the same error. ibm.power_aix.mount gives the same results.
