### ISSUE TITLE
lvol module fails when strip size not specified

### ISSUE THREAD

**Issue by bofhryan** [IBM/ansible-power-aix#95]
The lvol module fails to create a LV if a strip size is not specified:
fatal: [server]: FAILED! => {"changed": false, "cmd": "mklv -t jfs2 -y test_lv -c 1  -e x  -S None aixvg 64 ", "msg": "Failed to create logical volume test_lv in volume group volume_group. Command 'mklv -t jfs2 -y test_lv -c 1  -e x  -S None volume_group 64 ' failed.", "rc": 1, "stderr": "0516-1435 mklv: The -S parameter for stripe size must be a power\n\tof 2. (ex: 4K, 8K, 16K, 32K, 64K, 128K...1M, 2M...128M) \n", "stderr_lines": ["0516-1435 mklv: The -S parameter for stripe size must be a power", "\tof 2. (ex: 4K, 8K, 16K, 32K, 64K, 128K...1M, 2M...128M) "], "stdout": "", "stdout_lines": []}

**Comment by jdejoya17** [comment]
The latest version of lvol module should fix this problem.

Below is a test playbook, that does not need strip size to be specified.
```
---
- name: "Create a logical volume"
  hosts: lp3 
  remote_user: root
  collections:
  - ibm.power_aix
  
  tasks:
  - name: "Create Volume Group"
    lvg:
      state: present
      vg_name: datavg
      pvs: "hdisk1 hdisk2"

  - name: "Create a Logical Volume"
    lvol:
      state: present
      vg: datavg
      lv: testlv
      lv_type: jfs2
      num_of_logical_partitions: 10
```

Below is a snippet of the output of the playbook after running
```
[WARNING]: running playbook inside collection ibm.power_aix

PLAY [Create a logical volume] **********************************************************************

TASK [Gathering Facts] ******************************************************************************
[WARNING]: xxxxxx
ok: [xxx.xxx.xxx.xxx]

TASK [Create Volume Group] **************************************************************************
ok: [xxx.xxx.xxx.xxx]

TASK [Create a Logical Volume] **********************************************************************
changed: [xxx.xxx.xxx.xxx]

PLAY RECAP ******************************************************************************************
xxx.xxx.xxx.xxx                : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
