### ISSUE TITLE
ibm.power_aix.devices requires knowledge of current device state to know outcome of task

### ISSUE THREAD

**Issue by stephenulmer** [IBM/ansible-power-aix#98]
**Describe the bug**
ibm.power_aix.devices is capable of updating the attributes of a device, but it is necessary to know the *current* state of the device to know what the result of the task will be.

**To Reproduce**
The following task will silently *not* set the IP address on the interface if it is in the "defined" state, but will instead make the interface available. A following run would then yield different behavior and a different finished state.

```
    - ibm.power_aix.devices:
        device: "en4"
        state: available
        attributes:
          netaddr: "10.100.10.50"
          netmask: "255.255.255.0"
```

**Expected behavior**
The module should make the user's assertion about the state and attributes of a device true.

**Environment:**
 - OS: AIX 7.2TL5
 - Python Version: 2.7
 - AIX Collection Version: HEAD -> dev-collection
